import type { NextPage } from 'next'
import Head from 'next/head'
import Editor from '../components/Editor'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Editor />
      </main>
    </div>
  )
}

export default Home
